// Resolves the app version from git ONCE, at build time, and writes the generated
// module that @alfred/shared re-exports as APP_VERSION. The running app never shells
// out to git — it only reads the baked-in constant (see docs/DEPLOYMENT.md §App versioning).
//
// Invoked by @alfred/shared's `build` (and the root `predev`, which builds packages),
// so the value is fresh for both deployed artifacts and local runs. CI/containers can
// skip git entirely by passing APP_VERSION in the environment.
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

// Resolved relative to this script's own location, so it works regardless of the cwd
// the package manager invokes it from.
const out = fileURLToPath(new URL('../packages/shared/src/version.ts', import.meta.url))

const version =
  process.env.APP_VERSION?.trim() || // a CI / container build can inject it directly (empty = unset)
  (() => {
    try {
      return execSync('git describe --tags --long --always --dirty', { encoding: 'utf8' }).trim()
    } catch {
      return '0.0.0-unknown' // building outside a git checkout — signals the bake ran without git, not a runtime git dependency
    }
  })()

writeFileSync(
  out,
  `// GENERATED by scripts/gen-version.mjs at build time — do not edit (gitignored).\n` +
    // JSON.stringify so a tag name containing a quote/backslash can't emit invalid TS.
    `export const APP_VERSION = ${JSON.stringify(version)}\n`,
)
